ABBREV_TO_TEAM = {
    'Ana': 'Anaheim Ducks',
    'Ari': 'Arizona Coyotes',
    'Bos': 'Boston Bruins',
    'Buf': 'Buffalo Sabres',
    'Cgy': 'Calgary Flames',
    'Car': 'Carolina Hurricanes',
    'Chi': 'Chicago Blackhawks',
    'Col': 'Colorado Avalanche',
    'Cbj': 'Columbus Blue Jackets',
    'Dal': 'Dallas Stars',
    'Det': 'Detroit Red Wings',
    'Edm': 'Edmonton Oilers',
    'Fla': 'Florida Panthers',
    'Lak': 'Los Angeles Kings',
    'Min': 'Minnesota Wild',
    'Mtl': 'Montreal Canadiens',
    'Nsh': 'Nashville Predators',
    'Njd': 'New Jersey Devils',
    'Nyi': 'New York Islanders',
    'Nyr': 'New York Rangers',
    'Ott': 'Ottawa Senators',
    'Phi': 'Philadelphia Flyers',
    'Pit': 'Pittsburgh Penguins',
    'Sjs': 'San Jose Sharks',
    'Sea': 'Seattle Kraken',
    'Stl': 'St Louis Blues',
    'Tbl': 'Tampa Bay Lightning',
    'Tor': 'Toronto Maple Leafs',
    'Van': 'Vancouver Canucks',
    'Vgk': 'Vegas Golden Knights',
    'Wsh': 'Washington Capitals',
    'Wpg': 'Winnipeg Jets'
}